### ISSUE TITLE
Question about categories

### ISSUE THREAD

**Issue by arturo8602** [kyordhel/GPSRCmdGen2015#13]
We have a question about the categories and the GPSRCmdGen-master. Analyzing the categories of the rulebook and the command generator for the GPSR test, we have 3 categories, however when we are generating commands on category 2 the command generated is from category 3, like this:

Go after Charly from the TV to the kitchen

Meet Charly at the bookcase and come after them to the hall

Meet John at the TV and take them to the bookcase 

This does not let us have a clear differentiation between categories.

Ivette and Arturo, Team Golem

**Comment by kyordhel** [comment]
The generated commands seem to be compliant with Category 2, because:
- *them* can be used in english instead of him or her when the person's gender is unknown.
- *come after* is an idiomatic expression meaning *follow*
- *take X to* is an idiomatic expression for *guide to*

In any case, the Generator grammars should be updated to be gender congruent.
