### ISSUE TITLE
Code freeze date

### ISSUE THREAD

**Issue by thetaleofnarutouzumaki** [kyordhel/GPSRCmdGen2015#20]
ola,

I would like to request info on whether there is a possibility of announcing a "code freeze date" for the command generator.

thank you and
kind regards,
Mithun K

**Comment by kyordhel** [comment]
So far there is no "code freeze date" as such. However, the RoboCup@Home rulebook specifies that final grammars must be available at least one month before the competition. This means that we cannot change them anymore (other than minor fixes like typos and so). The last applied patch contained only minor fixes, but the core (tasks to be performed) weren't changed.

Script-wise, the command generator is composed of 3 parts:
- Main code
- Grammar files
- Data files

#### Main Code (C#)
The main code contains the logic of the generator. Although there is no restriction about modifying it, I've no plans to make any update in the coming months.

#### Grammar Files (embedded text files)
The grammar files define both, the set of tasks that can be requested to a robot and the way in which commands will be shaped. No changes to the assignable tasks have been made since February 21st. Regarding commands, only minor fixes were performed lately by a native English speaker. Is very unlikely this happens again for Montreal 2018.

During the competition, a subset of these gramar files will be used. This subset will be kept in secret by the TC and commands will be carefully selected to be grammatically, and pragmatically correct.

#### Data Files (xml knowledge bases)
These files will be updated during setup days and a new recompiled version of the generators with the embedded updated files will be distributed. This files include location names, people names, object names, predefined questions, etc.

**Comment by thetaleofnarutouzumaki** [comment]
Awesome, thank you.
