### ISSUE TITLE
Remaining grammar errors

### ISSUE THREAD

**Issue by msdejong** [kyordhel/GPSRCmdGen2015#22]
I see most of the grammar mistakes were corrected - thank you! There is still an issue with plural objects - maybe this is too annoying to fix, but I thought I would point it out. For example:

For SPR:
How many fireplace are in the kitchen - fireplace should be plural

For GPSR:
Tell me how many water/beer/pasta there are on the washbasin - how many glasses of water | how many beers / how much pasta

**Comment by msdejong** [comment]
Also, in the list of objects, "tooth paste" is usually "toothpaste"

**Comment by kyordhel** [comment]
@Michiel29 

**List of objects in Objects.xml:** The entire file will change in Montreal, so I find it a little bit pointless to really dig into it now. I can correct the toothpaste thingy though.

**Plurals and wild card replacement:** This is indeed a **BIG**, yet known, issue. The names of places, locations, and objects are stored in an xml file and randomly substituted during command/question generation. The wild card replacer has no knowledge about the words in the data files, it simply performs blind string replacement.

Although it is doable to incorporate plurals, it is not trivial. Pattern replacement is a naïve and error prone approach, so language knowledge should be incorporated. Therefore, the generator should include logic for sense disambiguation in order to perform correct replacements in most cases. However, for sentences like ```water => glass of water```, this would be still insufficient. Sentences need to be validated at a semantic or even at a pragmatic level.

So far, we are expecting contributions from the league's members to add these new features (that's why the code is open source). I must say there are no plans in short-term to fix this issue.

**Comment by msdejong** [comment]
Okay, thanks for the response!
