### ISSUE TITLE
Multiple locations with same name

### ISSUE THREAD

**Issue by miguelvidex** [kyordhel/GPSRCmdGen2015#24]
I would like to ask if it's possible to appear more than one location with the same name?

Like in the file [Locations.xml](https://github.com/kyordhel/GPSRCmdGen/blob/master/CommonFiles/Locations.xml), where there are two cabinets, one in the corridor and one in the kitchen.

**Comment by kyordhel** [comment]
If this is a question regarding the rules of RoboCup@Home, you should place the question [there](https://github.com/RoboCupAtHome/RuleBook/).

Regarding the generator itself, yes, it is possible. Let's say in your grammar you have the following rules:

```NT1 = Take {name} from the {location1} to the ({location2}|exit), and then meet me at the {location1}.```
```NT2 = Take {name} from the {location} to the ({location}|exit), and then meet me at the {location}.```

```NT1``` can produce the sentence

> *Take Mary from the bedroom to the exit, and then meet me at the bedroom.*

which has the same location twice, while ```NT2``` can not. This is because internally all numbered wild cards are sequentially replaced by numbered ones before assigning values to them.

The reason to implement such feature is to prevent undesired duplicated entries that might not be semantically correct when using pseudo-random generated numbers to choose replacements.

Now, regarding data files. Duplicate entries count as different instances, so yes. In that case ```NT2``` might produce a duplicate location. whether that's correct or not, is beyond the scope of the generator.

**Comment by miguelvidex** [comment]
Ok, thank you for your answer.
